# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Spr < Formula
  desc "Stacked Pull Requests on GitHub"
  homepage "https://github.com/ejoffe/spr"
  version "0.4.3"
  license "MIT"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/ejoffe/spr/releases/download/v0.4.3/spr_macos_x86_64.tar.gz"
    sha256 "f484635ae3f6a728ffe4cd572107bbcaa6863d06e0f8c5eeb812fc188d6f82af"
  end
  if OS.mac? && Hardware::CPU.arm?
    url "https://github.com/ejoffe/spr/releases/download/v0.4.3/spr_macos_arm64.tar.gz"
    sha256 "fea71f8fc027d687bca948c5433ce75568cafe147a20f15a949874ccdc1287c6"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/ejoffe/spr/releases/download/v0.4.3/spr_linux_x86_64.tar.gz"
    sha256 "4a5a4d578bebb6c4966d61e45238b88f3a81f4be4ceea094ccc9d75faa82fb5b"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/ejoffe/spr/releases/download/v0.4.3/spr_linux_arm64.tar.gz"
    sha256 "f4cfbb592f5ee6be8ca30f4a1bcacea6522d314c9813c16305494ab0a5738a7a"
  end

  def install
    bin.install "git-spr"
    bin.install "git-amend"
    bin.install "spr_commit_hook"
  end
end
