# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Spr < Formula
  desc "Stacked Pull Requests on GitHub"
  homepage "https://github.com/ejoffe/spr"
  version "0.14.7"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ejoffe/spr/releases/download/v0.14.7/spr_darwin_x86_64.tar.gz"
      sha256 "78f64ecd30849c61fa8cd94f939e644e8c1d1b483fbeb825a885bc03fb4d765a"

      def install
        bin.install "git-spr"
        bin.install "git-amend"
        bin.install "spr_reword_helper"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ejoffe/spr/releases/download/v0.14.7/spr_darwin_arm64.tar.gz"
      sha256 "d99ee6635c290259e11ce600274bffe0d12e97be2b112f53f936041978a394fa"

      def install
        bin.install "git-spr"
        bin.install "git-amend"
        bin.install "spr_reword_helper"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ejoffe/spr/releases/download/v0.14.7/spr_linux_arm64.tar.gz"
      sha256 "2cd66a69c5402bc1ec7f8e40b5a9637c3f4754dfca834e6979e45b5ee67a90d6"

      def install
        bin.install "git-spr"
        bin.install "git-amend"
        bin.install "spr_reword_helper"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/ejoffe/spr/releases/download/v0.14.7/spr_linux_x86_64.tar.gz"
      sha256 "67c5b1802f2557b928ea8f6425af4f597d8fafbb4dcae6c0087d26d239dac25a"

      def install
        bin.install "git-spr"
        bin.install "git-amend"
        bin.install "spr_reword_helper"
      end
    end
  end
end
