# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Spr < Formula
  desc "Stacked Pull Requests on GitHub"
  homepage "https://github.com/ejoffe/spr"
  version "0.14.8"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/ejoffe/spr/releases/download/v0.14.8/spr_darwin_arm64.tar.gz"
      sha256 "f52698f6ffcf18a91cc106f7cff8d00124864b09952a02cca4ac782cbe58cd63"

      def install
        bin.install "git-spr"
        bin.install "git-amend"
        bin.install "spr_reword_helper"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/ejoffe/spr/releases/download/v0.14.8/spr_darwin_x86_64.tar.gz"
      sha256 "98eb7f6dc024d5e5e7a12d68759bdf0172147a3b19c991bc13246e55f3aaf5e4"

      def install
        bin.install "git-spr"
        bin.install "git-amend"
        bin.install "spr_reword_helper"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ejoffe/spr/releases/download/v0.14.8/spr_linux_arm64.tar.gz"
      sha256 "ea0f1ab931cbd94330b0d8aaca5835216d921f38d9a1c2f64c26af2fff1abe99"

      def install
        bin.install "git-spr"
        bin.install "git-amend"
        bin.install "spr_reword_helper"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/ejoffe/spr/releases/download/v0.14.8/spr_linux_x86_64.tar.gz"
      sha256 "e72ae995358c42de8e6b66dc45bd474fae79643e3a5a65e52fc77c31bec198ee"

      def install
        bin.install "git-spr"
        bin.install "git-amend"
        bin.install "spr_reword_helper"
      end
    end
  end
end
